#Requires -Version 7.0
<#
.SYNOPSIS
  Bootstraps the modular PowerShell config — the Windows counterpart of bootstrap.sh.

.DESCRIPTION
  Backs up any existing profile, writes the loader, installs the PSGallery
  modules and the CLI tools the config expects, and optionally removes
  oh-my-posh (whose job the 11-prompt.ps1 module now does).

.PARAMETER SkipTools
  Do not install CLI tools via winget.

.PARAMETER SkipModules
  Do not install PowerShell modules from the PSGallery.

.PARAMETER RemoveOhMyPosh
  Uninstall oh-my-posh and strip its init line from the old profile.

.PARAMETER Force
  Answer yes to every prompt.
#>
[CmdletBinding()]
param(
  [switch]$SkipTools,
  [switch]$SkipModules,
  [switch]$RemoveOhMyPosh,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$PWSHRC_DIR = Split-Path -Parent $PSCommandPath

function Write-Step { param([string]$Msg) Write-Host "`n$Msg" -ForegroundColor Cyan }
function Write-Ok   { param([string]$Msg) Write-Host "  ✅ $Msg" -ForegroundColor Green }
function Write-Warn { param([string]$Msg) Write-Host "  ⚠️  $Msg" -ForegroundColor Yellow }
function Write-Info { param([string]$Msg) Write-Host "  ·  $Msg" -ForegroundColor DarkGray }

function Confirm-Action {
  param([string]$Question)
  if ($Force) { return $true }
  $a = Read-Host "$Question [y/N]"
  return $a -match '^[Yy]'
}

Write-Host '🛠️  Bootstrapping modular PowerShell config...' -ForegroundColor Magenta
Write-Info "Config directory: $PWSHRC_DIR"

# ─────────────────────────────────────────────────────────────────────
# 1. Sanity checks
# ─────────────────────────────────────────────────────────────────────
Write-Step '1. Checking the shell'

if ($PSVersionTable.PSEdition -ne 'Core') {
  Write-Warn 'This config targets PowerShell 7+ (pwsh). Windows PowerShell 5.1 is not supported.'
  Write-Warn 'Install it with:  winget install Microsoft.PowerShell'
  if (-not (Confirm-Action 'Continue anyway?')) { return }
} else {
  Write-Ok "PowerShell $($PSVersionTable.PSVersion)"
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  Write-Warn 'git is not on PATH — the git pills in the prompt will stay empty.'
}

# ─────────────────────────────────────────────────────────────────────
# 2. Back up the existing profile
# ─────────────────────────────────────────────────────────────────────
Write-Step '2. Backing up the existing profile'

$loaderTarget = $PROFILE.CurrentUserAllHosts
$hostProfile  = $PROFILE.CurrentUserCurrentHost
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$marker = '# ~/profile.ps1 (autogenerated by zshrc/windows/bootstrap.ps1)'

foreach ($p in @($loaderTarget, $hostProfile)) {
  if ((Test-Path -LiteralPath $p) -and (Get-Content -LiteralPath $p -Raw) -notmatch [regex]::Escape($marker)) {
    $backup = "$p.bak.$stamp"
    Copy-Item -LiteralPath $p -Destination $backup -Force
    Write-Ok "Backed up $(Split-Path -Leaf $p) → $(Split-Path -Leaf $backup)"
  }
}

$profileDir = Split-Path -Parent $loaderTarget
if (-not (Test-Path -LiteralPath $profileDir)) {
  New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# ─────────────────────────────────────────────────────────────────────
# 3. Write the loader
# ─────────────────────────────────────────────────────────────────────
Write-Step '3. Writing the profile loader'

$loader = @"
$marker
# Edit the modules in the repo, not this file.

`$global:PWSHRC_DIR = '$PWSHRC_DIR'

if (Test-Path -LiteralPath `$global:PWSHRC_DIR) {
  Get-ChildItem -LiteralPath `$global:PWSHRC_DIR -Filter '*.ps1' |
    Where-Object { `$_.Name -match '^\d{2}-' } |
    Sort-Object Name |
    ForEach-Object {
      try { . `$_.FullName }
      catch { Write-Warning "Failed to load `$(`$_.Name): `$(`$_.Exception.Message)" }
    }
} else {
  Write-Warning "PWSHRC_DIR not found: `$global:PWSHRC_DIR"
}
"@

Set-Content -LiteralPath $loaderTarget -Value $loader -Encoding utf8
Write-Ok "Loader written to $loaderTarget"

# The host-specific profile loads *after* the all-hosts one and would re-run
# the old oh-my-posh init on top of our prompt. Replace it with a pointer.
if (Test-Path -LiteralPath $hostProfile) {
  $hostContent = Get-Content -LiteralPath $hostProfile -Raw
  if ($hostContent -notmatch [regex]::Escape($marker)) {
    Set-Content -LiteralPath $hostProfile -Encoding utf8 -Value @"
$marker
# The real config lives in profile.ps1 (all hosts) → `$PWSHRC_DIR.
# Your previous contents were backed up alongside this file as *.bak.*
"@
    Write-Ok 'Neutralised the host-specific profile (it was overriding the prompt)'
  }
}

# ─────────────────────────────────────────────────────────────────────
# 4. oh-my-posh
# ─────────────────────────────────────────────────────────────────────
Write-Step '4. oh-my-posh'

$omp = Get-Command oh-my-posh -ErrorAction SilentlyContinue
if ($omp) {
  Write-Info "Found at $($omp.Source)"
  Write-Info '11-prompt.ps1 renders the prompt now, so oh-my-posh is redundant.'

  if ($RemoveOhMyPosh -or (Confirm-Action '  Uninstall oh-my-posh?')) {
    try {
      winget uninstall --id JanDeDobbeleer.OhMyPosh --silent --disable-interactivity
      Write-Ok 'oh-my-posh uninstalled'
    } catch {
      Write-Warn "winget uninstall failed: $($_.Exception.Message)"
    }

    # Leftover theme JSONs are harmless and may be hand-edited, so they are
    # reported rather than deleted — removing them is not part of "uninstall".
    $ompThemes = Join-Path $env:LOCALAPPDATA 'Programs\oh-my-posh'
    if (Test-Path -LiteralPath $ompThemes) {
      Write-Info "Leftover themes remain at $ompThemes — delete manually if you want them gone."
    }
  } else {
    Write-Info 'Left installed — it just is not initialised by this config.'
  }
} else {
  Write-Ok 'Not installed'
}

# ─────────────────────────────────────────────────────────────────────
# 5. PowerShell modules
# ─────────────────────────────────────────────────────────────────────
if (-not $SkipModules) {
  Write-Step '5. PowerShell modules'

  $modules = @(
    @{ Name = 'PSReadLine';          Why = 'line editing, vi mode, prediction' }
    @{ Name = 'posh-git';            Why = 'git tab-completion' }
    @{ Name = 'Terminal-Icons';      Why = 'icons in directory listings' }
    @{ Name = 'PSFzf';               Why = 'fzf-tab and Ctrl-R/Ctrl-T' }
    @{ Name = 'CompletionPredictor'; Why = 'completion-based predictions' }
  )

  $missing = $modules | Where-Object { -not (Get-Module -ListAvailable -Name $_.Name) }

  if (-not $missing) {
    Write-Ok 'All modules already installed'
  } else {
    Write-Host '  Missing modules:' -ForegroundColor Yellow
    $missing | ForEach-Object { Write-Host "    • $($_.Name) — $($_.Why)" }

    if (Confirm-Action '  Install them from the PSGallery?') {
      # Trust the gallery for this call only, rather than changing it globally
      foreach ($m in $missing) {
        try {
          Write-Info "Installing $($m.Name)..."
          Install-Module -Name $m.Name -Scope CurrentUser -Force -AllowClobber -AcceptLicense -Repository PSGallery
          Write-Ok "$($m.Name) installed"
        } catch {
          Write-Warn "$($m.Name): $($_.Exception.Message)"
        }
      }
    }
  }
} else {
  Write-Step '5. PowerShell modules — skipped'
}

# ─────────────────────────────────────────────────────────────────────
# 6. CLI tools
# ─────────────────────────────────────────────────────────────────────
if (-not $SkipTools) {
  Write-Step '6. CLI tools'

  if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Warn 'winget not found. Install "App Installer" from the Microsoft Store, then re-run.'
  } else {
    $tools = @(
      @{ Cmd = 'bat';    Id = 'sharkdp.bat';           Why = 'cat with syntax highlighting' }
      @{ Cmd = 'fzf';    Id = 'junegunn.fzf';          Why = 'fuzzy finder — fe, fcd, fh, tab completion' }
      @{ Cmd = 'zoxide'; Id = 'ajeetdsouza.zoxide';    Why = 'smarter cd' }
      @{ Cmd = 'eza';    Id = 'eza-community.eza';     Why = 'ls replacement' }
      @{ Cmd = 'fd';     Id = 'sharkdp.fd';            Why = 'find replacement' }
      @{ Cmd = 'rg';     Id = 'BurntSushi.ripgrep.MSVC'; Why = 'grep replacement — findtext' }
      @{ Cmd = 'yazi';   Id = 'sxyazi.yazi';           Why = 'terminal file manager — y' }
      @{ Cmd = 'nvim';   Id = 'Neovim.Neovim';         Why = '$EDITOR — n' }
      @{ Cmd = 'jq';     Id = 'jqlang.jq';             Why = 'JSON processing' }
      @{ Cmd = 'delta';  Id = 'dandavison.delta';      Why = 'better git diffs' }
      @{ Cmd = 'gsudo';  Id = 'gerardog.gsudo';        Why = 'sudo — please' }
      @{ Cmd = 'fnm';    Id = 'Schniz.fnm';            Why = 'node version manager (nvm equivalent)' }
    )

    $missingTools = $tools | Where-Object { -not (Get-Command $_.Cmd -ErrorAction SilentlyContinue) }

    if (-not $missingTools) {
      Write-Ok 'All CLI tools already installed'
    } else {
      Write-Host "  Missing $($missingTools.Count) of $($tools.Count) tools:" -ForegroundColor Yellow
      $missingTools | ForEach-Object { Write-Host ("    • {0,-8} {1,-28} {2}" -f $_.Cmd, $_.Id, $_.Why) }
      Write-Info 'The config degrades gracefully without them, but this is the intended set.'

      if (Confirm-Action '  Install them all with winget?') {
        foreach ($t in $missingTools) {
          Write-Info "Installing $($t.Cmd) ($($t.Id))..."
          winget install --id $t.Id --exact --silent --accept-package-agreements --accept-source-agreements --disable-interactivity
          if ($LASTEXITCODE -eq 0) { Write-Ok "$($t.Cmd) installed" }
          else { Write-Warn "$($t.Cmd) failed (winget exit $LASTEXITCODE)" }
        }
        $global:LASTEXITCODE = 0
        Write-Info 'Restart the shell so the new tools land on PATH.'
      }
    }
  }
} else {
  Write-Step '6. CLI tools — skipped'
}

# ─────────────────────────────────────────────────────────────────────
# 7. Nerd Font
# ─────────────────────────────────────────────────────────────────────
Write-Step '7. Nerd Font'

$fontDirs = @("$env:WINDIR\Fonts", "$env:LOCALAPPDATA\Microsoft\Windows\Fonts")
$hasNerd = $false
foreach ($d in $fontDirs) {
  if (Test-Path -LiteralPath $d) {
    if (Get-ChildItem -LiteralPath $d -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match 'NerdFont|Nerd Font' } | Select-Object -First 1) {
      $hasNerd = $true; break
    }
  }
}

if ($hasNerd) {
  Write-Ok 'A Nerd Font is installed'
  Write-Info 'Make sure your terminal profile actually selects it, or the prompt glyphs will show as boxes.'
} else {
  Write-Warn 'No Nerd Font found — the prompt icons will render as tofu boxes.'
  if (Confirm-Action '  Install JetBrainsMono Nerd Font via winget?') {
    winget install --id DEVCOM.JetBrainsMonoNerdFont --exact --silent --accept-package-agreements --accept-source-agreements
    $global:LASTEXITCODE = 0
  }
}

# ─────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────
Write-Host "`n🎉 PowerShell is ready. Reload with: " -NoNewline -ForegroundColor Magenta
Write-Host 'reload' -ForegroundColor White
Write-Host "   (or just open a new tab)`n" -ForegroundColor DarkGray
